# Generated by Django 5.2.4 on 2025-07-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('transcription', models.TextField()),
                ('ia_response', models.TextField()),
                ('tts_audio_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaticResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField()),
            ],
        ),
    ]
